package projetotdaepoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author jotap
 */
public class AplicarVacina extends javax.swing.JFrame {

    FinalizarConsulta fc = new FinalizarConsulta();
     ArrayList<Pessoa> pessoas = new ArrayList();
    ArrayList<Enfermeira> enfermeiras = new ArrayList();
    
    
    
    public AplicarVacina() {
        initComponents();
    }
    
    /**
     *
     * @param table
     */

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jftf_bcgNova = new javax.swing.JFormattedTextField();
        jftf_vopNova = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_dadosnovos = new javax.swing.JTable();
        jb_finalizaralterarcarteira = new javax.swing.JButton();
        jl_alterarcarteira = new javax.swing.JLabel();
        jl_doseNova = new javax.swing.JLabel();
        jl_idadePNova = new javax.swing.JLabel();
        jftf_tetravalenteNova = new javax.swing.JFormattedTextField();
        jftf_tripliceviralNova = new javax.swing.JFormattedTextField();
        jftf_hepatiteNova = new javax.swing.JFormattedTextField();
        jl_vacinadoNova = new javax.swing.JLabel();
        jl_duracaoNova = new javax.swing.JLabel();
        jl_idadeNova = new javax.swing.JLabel();
        jl_vacinadoNova1 = new javax.swing.JLabel();
        jftf_duplaNova = new javax.swing.JFormattedTextField();
        jb_aplicarvacinas = new javax.swing.JButton();
        jftf_idadePNovo = new javax.swing.JFormattedTextField();
        jl_vacinaNova1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(10, 162, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(64, 89, 201)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jftf_bcgNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_bcgNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_bcgNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_bcgNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_bcgNovaActionPerformed(evt);
            }
        });

        jftf_vopNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_vopNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_vopNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_vopNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_vopNovaActionPerformed(evt);
            }
        });

        jt_dadosnovos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jt_dadosnovos);

        jb_finalizaralterarcarteira.setBackground(new java.awt.Color(255, 204, 0));
        jb_finalizaralterarcarteira.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_finalizaralterarcarteira.setForeground(new java.awt.Color(255, 255, 255));
        jb_finalizaralterarcarteira.setText(" Finalizar");
        jb_finalizaralterarcarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_finalizaralterarcarteiraActionPerformed(evt);
            }
        });

        jl_alterarcarteira.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_alterarcarteira.setForeground(new java.awt.Color(255, 255, 255));
        jl_alterarcarteira.setText("Alterar Dados Carteira de Vacinação:");

        jl_doseNova.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_doseNova.setForeground(new java.awt.Color(255, 255, 255));
        jl_doseNova.setText("VOP:");

        jl_idadePNova.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_idadePNova.setForeground(new java.awt.Color(255, 255, 255));
        jl_idadePNova.setText("Idade:");

        jftf_tetravalenteNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_tetravalenteNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_tetravalenteNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_tetravalenteNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_tetravalenteNovaActionPerformed(evt);
            }
        });

        jftf_tripliceviralNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_tripliceviralNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_tripliceviralNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_tripliceviralNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_tripliceviralNovaActionPerformed(evt);
            }
        });

        jftf_hepatiteNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_hepatiteNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_hepatiteNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_hepatiteNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_hepatiteNovaActionPerformed(evt);
            }
        });

        jl_vacinadoNova.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_vacinadoNova.setForeground(new java.awt.Color(255, 255, 255));
        jl_vacinadoNova.setText("Dupla:");

        jl_duracaoNova.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_duracaoNova.setForeground(new java.awt.Color(255, 255, 255));
        jl_duracaoNova.setText("Tetravalente:");

        jl_idadeNova.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_idadeNova.setForeground(new java.awt.Color(255, 255, 255));
        jl_idadeNova.setText("Tríplice Viral:");

        jl_vacinadoNova1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_vacinadoNova1.setForeground(new java.awt.Color(255, 255, 255));
        jl_vacinadoNova1.setText("Hepatite B:");

        jftf_duplaNova.setBackground(new java.awt.Color(255, 204, 0));
        jftf_duplaNova.setForeground(new java.awt.Color(0, 0, 0));
        jftf_duplaNova.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_duplaNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_duplaNovaActionPerformed(evt);
            }
        });

        jb_aplicarvacinas.setBackground(new java.awt.Color(255, 204, 0));
        jb_aplicarvacinas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_aplicarvacinas.setForeground(new java.awt.Color(255, 255, 255));
        jb_aplicarvacinas.setText("Aplicar");
        jb_aplicarvacinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aplicarvacinasActionPerformed(evt);
            }
        });

        jftf_idadePNovo.setBackground(new java.awt.Color(255, 204, 0));
        jftf_idadePNovo.setForeground(new java.awt.Color(0, 0, 0));
        jftf_idadePNovo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_idadePNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_idadePNovoActionPerformed(evt);
            }
        });

        jl_vacinaNova1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_vacinaNova1.setForeground(new java.awt.Color(255, 255, 255));
        jl_vacinaNova1.setText("BCG:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_doseNova)
                    .addComponent(jftf_vopNova, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jftf_bcgNova)
                    .addComponent(jftf_tetravalenteNova)
                    .addComponent(jftf_tripliceviralNova)
                    .addComponent(jftf_hepatiteNova)
                    .addComponent(jl_vacinadoNova)
                    .addComponent(jl_idadePNova)
                    .addComponent(jl_vacinadoNova1)
                    .addComponent(jl_idadeNova)
                    .addComponent(jftf_duplaNova)
                    .addComponent(jftf_idadePNovo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jb_finalizaralterarcarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jl_alterarcarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jl_duracaoNova)
                    .addContainerGap(805, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jb_aplicarvacinas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(781, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jl_vacinaNova1)
                    .addContainerGap(922, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jl_idadePNova)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_alterarcarteira)
                    .addComponent(jftf_idadePNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jftf_bcgNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jl_doseNova)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_vopNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jftf_tetravalenteNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jl_idadeNova)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_tripliceviralNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jl_vacinadoNova1)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_hepatiteNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jl_vacinadoNova)
                        .addGap(18, 18, 18)
                        .addComponent(jftf_duplaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jb_finalizaralterarcarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(259, 259, 259)
                    .addComponent(jl_duracaoNova)
                    .addContainerGap(516, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(711, Short.MAX_VALUE)
                    .addComponent(jb_aplicarvacinas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addComponent(jl_vacinaNova1)
                    .addContainerGap(701, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftf_bcgNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_bcgNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_bcgNovaActionPerformed

    private void jftf_vopNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_vopNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_vopNovaActionPerformed

    private void jb_finalizaralterarcarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_finalizaralterarcarteiraActionPerformed
       
        
                
                fc = new FinalizarConsulta();
                fc.setLocationRelativeTo(null);
                fc.setVisible(true);  
                dispose();
         
    }//GEN-LAST:event_jb_finalizaralterarcarteiraActionPerformed

    private void jftf_tetravalenteNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_tetravalenteNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_tetravalenteNovaActionPerformed

    private void jftf_tripliceviralNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_tripliceviralNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_tripliceviralNovaActionPerformed

    private void jftf_hepatiteNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_hepatiteNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_hepatiteNovaActionPerformed

    private void jftf_duplaNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_duplaNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_duplaNovaActionPerformed

    private void jb_aplicarvacinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aplicarvacinasActionPerformed

        Enfermeira objenf = new Enfermeira();
        
        
        
       String coren = JOptionPane.showInputDialog(null, "Digite o COREN da(o) Enfermeira(o)");            
       String senhaE = JOptionPane.showInputDialog(null, "Digite a senha da(o) Enfermeira(o)");

       if(coren.equals("12345") && senhaE.equalsIgnoreCase("senha123")){

                JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Enfermeiro(a)", JOptionPane.INFORMATION_MESSAGE);
                
                objenf.setAplicarVacina("Aplicar Vacina!");  // Método AplicarVacina da enfermeira, está certo?
                
                JOptionPane.showMessageDialog(null, objenf.getAplicarVacina());  
                
                String titulos[] = {"Vacinas", "0-2 Anos", "3 - 9 Anos", "10 - 18 Anos", "Acima dos 18 Anos", "Vacinado(a)", "Idade Paciente"};
                Object dados[][] = {
            
                {"BCG", "0.25 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_bcgNova.getText(), jftf_idadePNovo.getText()},      
                {"VOP", "0.10 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_vopNova.getText(), jftf_idadePNovo.getText()},
                {"TETRAVALENTE", "0.30 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_tetravalenteNova.getText(),jftf_idadePNovo.getText()},
                {"TRIPLICE VIRAL", "1.00 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_tripliceviralNova.getText(),jftf_idadePNovo.getText()},
                {"HEPATITE B", "0.75 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_hepatiteNova.getText(), jftf_idadePNovo.getText()},
                {"DUPLA", "0.20 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_duplaNova.getText(), jftf_idadePNovo.getText()},
        };
                DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
                jt_dadosnovos.setModel(modelo);
            }
            
            else{
                
                
                JOptionPane.showMessageDialog(null, "Autorização negada para alterar dados do Paciente");
                
            }



       
            for(int i=0; i<pessoas.size(); i++){

            Pessoa en = pessoas.get(i);
            Enfermeira enf = enfermeiras.get(i);
            
            if(coren.equals(enf.getCoren()) && senhaE.equalsIgnoreCase(en.getSenha())){

                JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Enfermeiro(a)", JOptionPane.INFORMATION_MESSAGE);
                String titulos[] = {"Vacinas", "0-2 Anos", "3 - 9 Anos", "10 - 18 Anos", "Acima dos 18 Anos", "Vacinado(a)", "Idade Paciente"};
                Object dados[][] = {
            
                {"BCG", "0.25 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_bcgNova.getText(), jftf_idadePNovo.getText()},      
                {"VOP", "0.10 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_vopNova.getText(), jftf_idadePNovo.getText()},
                {"TETRAVALENTE", "0.30 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_tetravalenteNova.getText(),jftf_idadePNovo.getText()},
                {"TRIPLICE VIRAL", "1.00 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_tripliceviralNova.getText(),jftf_idadePNovo.getText()},
                {"HEPATITE B", "0.75 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_hepatiteNova.getText(), jftf_idadePNovo.getText()},
                {"DUPLA", "0.20 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", jftf_duplaNova.getText(), jftf_idadePNovo.getText()},
        };
                DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
                jt_dadosnovos.setModel(modelo);
                break;
            }
            
            else{
                
                
                JOptionPane.showMessageDialog(null, "Autorização negada para alterar dados do Paciente");
                break;
                
            }}
    }//GEN-LAST:event_jb_aplicarvacinasActionPerformed

    private void jftf_idadePNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_idadePNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_idadePNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicarVacina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_aplicarvacinas;
    private javax.swing.JButton jb_finalizaralterarcarteira;
    private javax.swing.JFormattedTextField jftf_bcgNova;
    private javax.swing.JFormattedTextField jftf_duplaNova;
    private javax.swing.JFormattedTextField jftf_hepatiteNova;
    private javax.swing.JFormattedTextField jftf_idadePNovo;
    private javax.swing.JFormattedTextField jftf_tetravalenteNova;
    private javax.swing.JFormattedTextField jftf_tripliceviralNova;
    private javax.swing.JFormattedTextField jftf_vopNova;
    private javax.swing.JLabel jl_alterarcarteira;
    private javax.swing.JLabel jl_doseNova;
    private javax.swing.JLabel jl_duracaoNova;
    private javax.swing.JLabel jl_idadeNova;
    private javax.swing.JLabel jl_idadePNova;
    private javax.swing.JLabel jl_vacinaNova1;
    private javax.swing.JLabel jl_vacinadoNova;
    private javax.swing.JLabel jl_vacinadoNova1;
    private javax.swing.JTable jt_dadosnovos;
    // End of variables declaration//GEN-END:variables

}
