package projetotdaepoo;

import java.util.ArrayList;
import javax.persistence.Table;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jotap
 */
public class JanelaCarteira extends javax.swing.JFrame {

   ArrayList<Paciente> dadoscarteiravac = new ArrayList();  
   VerificarCarteira enviartabela;
   
    
    public JanelaCarteira() {
        initComponents();
    }
    
       public void exportarIdade (DadosUsuario model){
    
        tf_idadeP.setText(model.getIdade()); 
    }
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_bcg = new javax.swing.ButtonGroup();
        bg_vop = new javax.swing.ButtonGroup();
        bg_tretavalente = new javax.swing.ButtonGroup();
        bg_tripliceviral = new javax.swing.ButtonGroup();
        bg_hepatiteb = new javax.swing.ButtonGroup();
        bg_dupla = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jp_dadosP = new javax.swing.JScrollPane();
        jt_carteiravacinacao = new javax.swing.JTable();
        jb_marcarconsulta = new javax.swing.JButton();
        jl_vop = new javax.swing.JLabel();
        jl_dupla = new javax.swing.JLabel();
        jl_tripliceviral = new javax.swing.JLabel();
        jl_tretavalente = new javax.swing.JLabel();
        jl_bcg = new javax.swing.JLabel();
        jl_hepatiteb = new javax.swing.JLabel();
        jl_vacinado = new javax.swing.JLabel();
        tf_vopP = new javax.swing.JTextField();
        tf_tretavalenteP = new javax.swing.JTextField();
        tf_tripliceviralP = new javax.swing.JTextField();
        tf_hepatitebP = new javax.swing.JTextField();
        tf_duplaP = new javax.swing.JTextField();
        tf_bcgP = new javax.swing.JTextField();
        jb_salvarcarteira1 = new javax.swing.JButton();
        tf_idadeP = new javax.swing.JTextField();
        jl_idadeP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));

        jPanel1.setBackground(new java.awt.Color(10, 162, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(64, 89, 201)));

        jt_carteiravacinacao.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jt_carteiravacinacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jt_carteiravacinacao.setAutoscrolls(false);
        jt_carteiravacinacao.setIntercellSpacing(new java.awt.Dimension(3, 3));
        jp_dadosP.setViewportView(jt_carteiravacinacao);

        jb_marcarconsulta.setBackground(new java.awt.Color(255, 204, 0));
        jb_marcarconsulta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_marcarconsulta.setForeground(new java.awt.Color(255, 255, 255));
        jb_marcarconsulta.setText("Marcar Consulta");
        jb_marcarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_marcarconsultaActionPerformed(evt);
            }
        });

        jl_vop.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_vop.setForeground(new java.awt.Color(255, 255, 255));
        jl_vop.setText("VOP:");

        jl_dupla.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_dupla.setForeground(new java.awt.Color(255, 255, 255));
        jl_dupla.setText("Dupla ");

        jl_tripliceviral.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_tripliceviral.setForeground(new java.awt.Color(255, 255, 255));
        jl_tripliceviral.setText("Tríplice Viral:");

        jl_tretavalente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_tretavalente.setForeground(new java.awt.Color(255, 255, 255));
        jl_tretavalente.setText("Tretavalente:");

        jl_bcg.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_bcg.setForeground(new java.awt.Color(255, 255, 255));
        jl_bcg.setText("BCG:");

        jl_hepatiteb.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_hepatiteb.setForeground(new java.awt.Color(255, 255, 255));
        jl_hepatiteb.setText("Hepatite B:");

        jl_vacinado.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jl_vacinado.setForeground(new java.awt.Color(255, 255, 255));
        jl_vacinado.setText("Vacinado(a): Sim ou Não ");

        tf_vopP.setBackground(new java.awt.Color(255, 204, 0));
        tf_vopP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_vopP.setForeground(new java.awt.Color(0, 0, 0));

        tf_tretavalenteP.setBackground(new java.awt.Color(255, 204, 0));
        tf_tretavalenteP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_tretavalenteP.setForeground(new java.awt.Color(0, 0, 0));

        tf_tripliceviralP.setBackground(new java.awt.Color(255, 204, 0));
        tf_tripliceviralP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_tripliceviralP.setForeground(new java.awt.Color(0, 0, 0));
        tf_tripliceviralP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tripliceviralPActionPerformed(evt);
            }
        });

        tf_hepatitebP.setBackground(new java.awt.Color(255, 204, 0));
        tf_hepatitebP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_hepatitebP.setForeground(new java.awt.Color(0, 0, 0));

        tf_duplaP.setBackground(new java.awt.Color(255, 204, 0));
        tf_duplaP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_duplaP.setForeground(new java.awt.Color(0, 0, 0));

        tf_bcgP.setBackground(new java.awt.Color(255, 204, 0));
        tf_bcgP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_bcgP.setForeground(new java.awt.Color(0, 0, 0));

        jb_salvarcarteira1.setBackground(new java.awt.Color(255, 204, 0));
        jb_salvarcarteira1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_salvarcarteira1.setForeground(new java.awt.Color(255, 255, 255));
        jb_salvarcarteira1.setText("Salvar");
        jb_salvarcarteira1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarcarteira1ActionPerformed(evt);
            }
        });

        tf_idadeP.setBackground(new java.awt.Color(255, 204, 0));
        tf_idadeP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_idadeP.setForeground(new java.awt.Color(0, 0, 0));
        tf_idadeP.setSelectionColor(new java.awt.Color(204, 204, 255));
        tf_idadeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idadePActionPerformed(evt);
            }
        });

        jl_idadeP.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_idadeP.setForeground(new java.awt.Color(255, 255, 255));
        jl_idadeP.setText("Idade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_marcarconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_vop)
                            .addComponent(jl_bcg)
                            .addComponent(jl_tripliceviral)
                            .addComponent(jl_dupla)
                            .addComponent(jl_hepatiteb)
                            .addComponent(jl_tretavalente)
                            .addComponent(jl_vacinado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_vopP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_bcgP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tretavalenteP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_tripliceviralP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hepatitebP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_duplaP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jp_dadosP, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_idadeP)
                        .addGap(37, 37, 37)
                        .addComponent(tf_idadeP, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jb_salvarcarteira1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_vacinado)
                    .addComponent(tf_idadeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_idadeP))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_bcg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_bcgP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jl_vop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_vopP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jl_tretavalente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_tretavalenteP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jl_tripliceviral)
                        .addGap(13, 13, 13)
                        .addComponent(tf_tripliceviralP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_hepatiteb)
                        .addGap(31, 31, 31)
                        .addComponent(tf_hepatitebP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_dupla))
                    .addComponent(jp_dadosP))
                .addGap(27, 27, 27)
                .addComponent(tf_duplaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jb_salvarcarteira1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_marcarconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_marcarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_marcarconsultaActionPerformed

            MarcarConsulta mcs = new MarcarConsulta();
            
            mcs.setLocation(200,200);
            mcs.setVisible(true);
           
        
           
       
    }//GEN-LAST:event_jb_marcarconsultaActionPerformed

    private void tf_tripliceviralPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tripliceviralPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tripliceviralPActionPerformed

    private void jb_salvarcarteira1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarcarteira1ActionPerformed
        
               
        String titulos[] = {"Vacinas", "0-2 Anos", "3 - 9 Anos", "10 - 18 Anos", "Acima dos 18 Anos", "Vacinado(a)"};
        Object dados[][] = {
            
        {"BCG", "0.25 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_bcgP.getText()},      
        {"VOP", "0.10 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_vopP.getText()},
        {"TETRAVALENTE", "0.30 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_tretavalenteP.getText()},
        {"TRIPLICE VIRAL", "1.00 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_tripliceviralP.getText()},
        {"HEPATITE B", "0.75 (ml)",  "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_hepatitebP.getText()},
        {"DUPLA", "0.20 (ml)", "0.45 (ml)", "0.50 (ml)", "0.56 (ml)", tf_duplaP.getText()},
};
        DefaultTableModel modelo = new DefaultTableModel(dados, titulos);
        jt_carteiravacinacao.setModel(modelo);
        
      
    }//GEN-LAST:event_jb_salvarcarteira1ActionPerformed

    private void tf_idadePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idadePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idadePActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCarteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCarteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCarteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCarteira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCarteira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_bcg;
    private javax.swing.ButtonGroup bg_dupla;
    private javax.swing.ButtonGroup bg_hepatiteb;
    private javax.swing.ButtonGroup bg_tretavalente;
    private javax.swing.ButtonGroup bg_tripliceviral;
    private javax.swing.ButtonGroup bg_vop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_marcarconsulta;
    private javax.swing.JButton jb_salvarcarteira1;
    private javax.swing.JLabel jl_bcg;
    private javax.swing.JLabel jl_dupla;
    private javax.swing.JLabel jl_hepatiteb;
    private javax.swing.JLabel jl_idadeP;
    private javax.swing.JLabel jl_tretavalente;
    private javax.swing.JLabel jl_tripliceviral;
    private javax.swing.JLabel jl_vacinado;
    private javax.swing.JLabel jl_vop;
    private javax.swing.JScrollPane jp_dadosP;
    private javax.swing.JTable jt_carteiravacinacao;
    private javax.swing.JTextField tf_bcgP;
    private javax.swing.JTextField tf_duplaP;
    private javax.swing.JTextField tf_hepatitebP;
    private javax.swing.JTextField tf_idadeP;
    private javax.swing.JTextField tf_tretavalenteP;
    private javax.swing.JTextField tf_tripliceviralP;
    private javax.swing.JTextField tf_vopP;
    // End of variables declaration//GEN-END:variables

}


