/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotdaepoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jotap
 */
public class LoginMedicos extends javax.swing.JFrame {

    
    ArrayList<Pessoa> pessoas = new ArrayList();
    ArrayList<Medico> medicos = new ArrayList();
    /**
     * Creates new form LoginMedicos
     */
    public LoginMedicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_senhaM = new javax.swing.JLabel();
        jl_crmM = new javax.swing.JLabel();
        jftf_usuarioM = new javax.swing.JFormattedTextField();
        jb_entrarM = new javax.swing.JButton();
        jftf_senhaM = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 162, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(64, 89, 201)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jl_senhaM.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_senhaM.setForeground(new java.awt.Color(255, 255, 255));
        jl_senhaM.setText("Senha:");

        jl_crmM.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_crmM.setForeground(new java.awt.Color(255, 255, 255));
        jl_crmM.setText("CRM:");

        jftf_usuarioM.setBackground(new java.awt.Color(255, 204, 0));
        jftf_usuarioM.setForeground(new java.awt.Color(0, 0, 0));
        jftf_usuarioM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_usuarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_usuarioMActionPerformed(evt);
            }
        });

        jb_entrarM.setBackground(new java.awt.Color(255, 204, 0));
        jb_entrarM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_entrarM.setForeground(new java.awt.Color(255, 255, 255));
        jb_entrarM.setText("Entrar");
        jb_entrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarMActionPerformed(evt);
            }
        });

        jftf_senhaM.setBackground(new java.awt.Color(255, 204, 0));
        jftf_senhaM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jftf_senhaM.setForeground(new java.awt.Color(0, 0, 0));
        jftf_senhaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jftf_senhaMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jl_senhaM, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jftf_usuarioM, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jftf_senhaM))
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(jb_entrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jl_crmM)
                    .addContainerGap(604, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jftf_usuarioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_senhaM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftf_senhaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(128, 128, 128)
                .addComponent(jb_entrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jl_crmM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jftf_usuarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_usuarioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_usuarioMActionPerformed

    private void jb_entrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarMActionPerformed

        String usuarioM = jftf_usuarioM.getText();
        int usuarioMCRM = Integer.parseInt(jftf_usuarioM.getText());
        String senhaM = jftf_senhaM.getText();
        VerificarCarteira vc = new VerificarCarteira();

        /*=====Médico João Pedro=====*/

        if(usuarioMCRM == 23162571 && senhaM.equalsIgnoreCase("joaozinho")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        }

        /*=====Médico Lucas=====*/

        else if(usuarioMCRM == 23171421 && senhaM.equalsIgnoreCase("unicsul2020")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        }

        /*=====Médico Cléber=====*/

        else if(usuarioMCRM == 10101010 && senhaM.equalsIgnoreCase("melhorprofessor")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        }

        /*=====Médico Aline=====*/

        else if(usuarioMCRM == 23048841 && senhaM.equalsIgnoreCase("alines2001")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        }

        /*=====Médico Geovanna=====*/

        else if(usuarioMCRM == 123456789 && senhaM.equalsIgnoreCase("geooo")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        }

        /*=====Médico Marco Antonio=====*/

        else if(usuarioMCRM == 987654321 && senhaM.equalsIgnoreCase("obrabodojava")){

            JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)"  + usuarioMCRM, JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
            vc.setLocationRelativeTo(null);
            vc.setVisible(true);
            dispose();

        } else{
        
            JOptionPane.showMessageDialog(null, " Usuário ou Senha inválidos, tente novamente" , "Sistema de Vacina", JOptionPane.ERROR_MESSAGE);
        }

        for(int i=0; i<pessoas.size(); i++){

            Pessoa med = pessoas.get(i);
            Medico med2 = medicos.get(i);

            if(usuarioM.equals(med2.getcrm()) && senhaM.equalsIgnoreCase(med.getSenha())){

                JOptionPane.showMessageDialog(null, " Logado com sucesso!" , "Bem-vindo(a) Doutor(a)" + usuarioM, JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(null, "Sistema de Verificação da carteira de Vacinação");
                vc.setLocationRelativeTo(null);
                vc.setVisible(true);
                dispose();
                break;
            }

            else{

                JOptionPane.showMessageDialog(null, " Usuário ou Senha inválidos, tente novamente" , "Sistema de Vacina", JOptionPane.ERROR_MESSAGE);
                break;
            }

        }

    }//GEN-LAST:event_jb_entrarMActionPerformed

    private void jftf_senhaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jftf_senhaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jftf_senhaMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_entrarM;
    private javax.swing.JPasswordField jftf_senhaM;
    private javax.swing.JFormattedTextField jftf_usuarioM;
    private javax.swing.JLabel jl_crmM;
    private javax.swing.JLabel jl_senhaM;
    // End of variables declaration//GEN-END:variables
}
