/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetotdaepoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jotap
 */
public class SistemaHome extends javax.swing.JFrame {

   ArrayList<Paciente> pacientes = new ArrayList();
   ArrayList<Pessoa> pessoas = new ArrayList();
   ArrayList<Medico> medicos = new ArrayList();
   VerificarCarteira enviarnome; 

    Paciente p = new Paciente();
    
    /**
     * Creates new form SistemaHome
     */
    public SistemaHome() {
        initComponents();
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtp_opcInicio = new javax.swing.JTabbedPane();
        jp_inicio = new javax.swing.JPanel();
        jl_logotipo = new javax.swing.JLabel();
        jl_nomehospital = new javax.swing.JLabel();
        jp_cadastrar = new javax.swing.JPanel();
        jtp_cadUsuarios = new javax.swing.JTabbedPane();
        jp_cadPaciente = new javax.swing.JPanel();
        jl_nomeP = new javax.swing.JLabel();
        jl_cpfP = new javax.swing.JLabel();
        jl_enderecoP = new javax.swing.JLabel();
        jl_telefoneP = new javax.swing.JLabel();
        jl_idadeP = new javax.swing.JLabel();
        jl_emailP = new javax.swing.JLabel();
        jl_senhaP = new javax.swing.JLabel();
        tf_emailP = new javax.swing.JFormattedTextField();
        tf_cpfP = new javax.swing.JFormattedTextField();
        tf_idadeP = new javax.swing.JFormattedTextField();
        tf_nomeP = new javax.swing.JFormattedTextField();
        tf_telefoneP = new javax.swing.JFormattedTextField();
        tf_enderecoP = new javax.swing.JFormattedTextField();
        jb_cadastrarP = new javax.swing.JButton();
        tf_senhaP = new javax.swing.JPasswordField();
        jp_cadMedico = new javax.swing.JPanel();
        jl_nomeM = new javax.swing.JLabel();
        jl_usuarioM = new javax.swing.JLabel();
        jl_areaAtuanteM = new javax.swing.JLabel();
        jl_crmM = new javax.swing.JLabel();
        jl_emailM = new javax.swing.JLabel();
        jl_senhaM = new javax.swing.JLabel();
        jb_cadastrarM = new javax.swing.JButton();
        tf_usuarioM = new javax.swing.JFormattedTextField();
        tf_nomeM = new javax.swing.JFormattedTextField();
        tf_areaAtuanteM = new javax.swing.JFormattedTextField();
        tf_crmM = new javax.swing.JFormattedTextField();
        tf_emailM = new javax.swing.JFormattedTextField();
        tf_senhaM = new javax.swing.JPasswordField();
        jp_cadEnfermeira = new javax.swing.JPanel();
        jl_nomeE = new javax.swing.JLabel();
        jl_corenE = new javax.swing.JLabel();
        jl_usuarioE = new javax.swing.JLabel();
        jl_senhaE = new javax.swing.JLabel();
        jl_telefoneE = new javax.swing.JLabel();
        jb_cadastrarE = new javax.swing.JButton();
        tf_nomeE = new javax.swing.JFormattedTextField();
        tf_usuarioE = new javax.swing.JFormattedTextField();
        tf_telefoneE = new javax.swing.JFormattedTextField();
        tf_corenE = new javax.swing.JFormattedTextField();
        pf_senhaE = new javax.swing.JPasswordField();
        jp_entrarBackground = new javax.swing.JPanel();
        jtp_entrarP = new javax.swing.JTabbedPane();
        jp_entrar = new javax.swing.JPanel();
        jl_email_tel_Entrar_P = new javax.swing.JLabel();
        jl_senha_Entrar_P = new javax.swing.JLabel();
        jb_entrarP = new javax.swing.JButton();
        tf_email_Entrar_P = new javax.swing.JTextField();
        tf_senha_Entrar_P = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtp_opcInicio.setBackground(new java.awt.Color(141, 194, 226));
        jtp_opcInicio.setForeground(new java.awt.Color(255, 255, 255));
        jtp_opcInicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jp_inicio.setBackground(new java.awt.Color(64, 89, 201));
        jp_inicio.setForeground(new java.awt.Color(255, 255, 255));

        jl_logotipo.setBackground(new java.awt.Color(51, 204, 0));
        jl_logotipo.setForeground(new java.awt.Color(255, 255, 255));
        jl_logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Santo Alcides Official.jpg"))); // NOI18N
        jl_logotipo.setMaximumSize(new java.awt.Dimension(200, 200));
        jl_logotipo.setMinimumSize(new java.awt.Dimension(500, 500));
        jl_logotipo.setPreferredSize(new java.awt.Dimension(200, 200));

        jl_nomehospital.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_nomehospital.setForeground(new java.awt.Color(255, 255, 255));
        jl_nomehospital.setText("Hospital Santo Caio Mil Grau");

        javax.swing.GroupLayout jp_inicioLayout = new javax.swing.GroupLayout(jp_inicio);
        jp_inicio.setLayout(jp_inicioLayout);
        jp_inicioLayout.setHorizontalGroup(
            jp_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inicioLayout.createSequentialGroup()
                .addGroup(jp_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_inicioLayout.createSequentialGroup()
                        .addGap(1773, 1773, 1773)
                        .addComponent(jl_nomehospital))
                    .addGroup(jp_inicioLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jl_logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_inicioLayout.setVerticalGroup(
            jp_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_inicioLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jl_logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_nomehospital)
                .addGap(61, 61, 61))
        );

        jtp_opcInicio.addTab("Início", jp_inicio);

        jp_cadastrar.setBackground(new java.awt.Color(64, 89, 201));
        jp_cadastrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(23, 142, 206)));
        jp_cadastrar.setForeground(new java.awt.Color(255, 255, 255));

        jtp_cadUsuarios.setBackground(new java.awt.Color(141, 194, 226));
        jtp_cadUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jtp_cadUsuarios.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jp_cadPaciente.setBackground(new java.awt.Color(10, 162, 255));
        jp_cadPaciente.setForeground(new java.awt.Color(255, 255, 255));
        jp_cadPaciente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jl_nomeP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_nomeP.setForeground(new java.awt.Color(255, 255, 255));
        jl_nomeP.setText("Nome:");

        jl_cpfP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_cpfP.setForeground(new java.awt.Color(255, 255, 255));
        jl_cpfP.setText("CPF:");

        jl_enderecoP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_enderecoP.setForeground(new java.awt.Color(255, 255, 255));
        jl_enderecoP.setText("Endereço:");

        jl_telefoneP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_telefoneP.setForeground(new java.awt.Color(255, 255, 255));
        jl_telefoneP.setText("Telefone:");

        jl_idadeP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_idadeP.setForeground(new java.awt.Color(255, 255, 255));
        jl_idadeP.setText("Idade:");

        jl_emailP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_emailP.setForeground(new java.awt.Color(255, 255, 255));
        jl_emailP.setText("E-mail:");

        jl_senhaP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_senhaP.setForeground(new java.awt.Color(255, 255, 255));
        jl_senhaP.setText("Senha:");

        tf_emailP.setBackground(new java.awt.Color(255, 204, 0));
        tf_emailP.setForeground(new java.awt.Color(0, 0, 0));
        tf_emailP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_cpfP.setBackground(new java.awt.Color(255, 204, 0));
        tf_cpfP.setForeground(new java.awt.Color(0, 0, 0));
        tf_cpfP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_cpfP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfPActionPerformed(evt);
            }
        });

        tf_idadeP.setBackground(new java.awt.Color(255, 204, 0));
        tf_idadeP.setForeground(new java.awt.Color(0, 0, 0));
        tf_idadeP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_idadeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idadePActionPerformed(evt);
            }
        });

        tf_nomeP.setBackground(new java.awt.Color(255, 204, 0));
        tf_nomeP.setForeground(new java.awt.Color(0, 0, 0));
        tf_nomeP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_nomeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomePActionPerformed(evt);
            }
        });

        tf_telefoneP.setBackground(new java.awt.Color(255, 204, 0));
        tf_telefoneP.setForeground(new java.awt.Color(0, 0, 0));
        tf_telefoneP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_telefoneP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefonePActionPerformed(evt);
            }
        });

        tf_enderecoP.setBackground(new java.awt.Color(255, 204, 0));
        tf_enderecoP.setForeground(new java.awt.Color(0, 0, 0));
        tf_enderecoP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jb_cadastrarP.setBackground(new java.awt.Color(255, 204, 0));
        jb_cadastrarP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_cadastrarP.setForeground(new java.awt.Color(255, 255, 255));
        jb_cadastrarP.setText("Cadastrar");
        jb_cadastrarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cadastrarPMouseClicked(evt);
            }
        });
        jb_cadastrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarPActionPerformed(evt);
            }
        });

        tf_senhaP.setBackground(new java.awt.Color(255, 204, 0));
        tf_senhaP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_senhaP.setForeground(new java.awt.Color(0, 0, 0));
        tf_senhaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senhaPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_cadPacienteLayout = new javax.swing.GroupLayout(jp_cadPaciente);
        jp_cadPaciente.setLayout(jp_cadPacienteLayout);
        jp_cadPacienteLayout.setHorizontalGroup(
            jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_senhaP)
                                    .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jl_emailP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jl_telefoneP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)
                                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_telefoneP)
                                    .addComponent(tf_emailP)
                                    .addComponent(tf_senhaP)))
                            .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_idadeP)
                                    .addComponent(jl_cpfP)
                                    .addComponent(jl_nomeP))
                                .addGap(50, 50, 50)
                                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_idadeP, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                                    .addComponent(tf_nomeP)
                                    .addComponent(tf_cpfP)))
                            .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                                .addComponent(jl_enderecoP)
                                .addGap(18, 18, 18)
                                .addComponent(tf_enderecoP, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jb_cadastrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jp_cadPacienteLayout.setVerticalGroup(
            jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nomeP)
                    .addComponent(tf_nomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_idadeP)
                    .addComponent(tf_idadeP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_cpfP)
                    .addComponent(tf_cpfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cadPacienteLayout.createSequentialGroup()
                        .addComponent(jl_emailP)
                        .addGap(18, 18, 18)
                        .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_senhaP)
                            .addComponent(tf_senhaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_telefoneP)
                            .addComponent(tf_telefoneP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_cadPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_enderecoP)
                            .addComponent(tf_enderecoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_emailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cadastrarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jtp_cadUsuarios.addTab("Paciente", jp_cadPaciente);

        jp_cadMedico.setBackground(new java.awt.Color(10, 162, 255));
        jp_cadMedico.setForeground(new java.awt.Color(255, 255, 255));

        jl_nomeM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_nomeM.setForeground(new java.awt.Color(255, 255, 255));
        jl_nomeM.setText("Nome:");

        jl_usuarioM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_usuarioM.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuarioM.setText("Usuário:");

        jl_areaAtuanteM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_areaAtuanteM.setForeground(new java.awt.Color(255, 255, 255));
        jl_areaAtuanteM.setText("Área Atuante:");

        jl_crmM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_crmM.setForeground(new java.awt.Color(255, 255, 255));
        jl_crmM.setText("CRM:");

        jl_emailM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_emailM.setForeground(new java.awt.Color(255, 255, 255));
        jl_emailM.setText("E-mail:");

        jl_senhaM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_senhaM.setForeground(new java.awt.Color(255, 255, 255));
        jl_senhaM.setText("Senha:");

        jb_cadastrarM.setBackground(new java.awt.Color(255, 204, 0));
        jb_cadastrarM.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_cadastrarM.setForeground(new java.awt.Color(255, 255, 255));
        jb_cadastrarM.setText("Cadastrar");
        jb_cadastrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarMActionPerformed(evt);
            }
        });

        tf_usuarioM.setBackground(new java.awt.Color(255, 204, 0));
        tf_usuarioM.setForeground(new java.awt.Color(0, 0, 0));
        tf_usuarioM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_nomeM.setBackground(new java.awt.Color(255, 204, 0));
        tf_nomeM.setForeground(new java.awt.Color(0, 0, 0));
        tf_nomeM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_areaAtuanteM.setBackground(new java.awt.Color(255, 204, 0));
        tf_areaAtuanteM.setForeground(new java.awt.Color(0, 0, 0));
        tf_areaAtuanteM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_crmM.setBackground(new java.awt.Color(255, 204, 0));
        tf_crmM.setForeground(new java.awt.Color(0, 0, 0));
        tf_crmM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_emailM.setBackground(new java.awt.Color(255, 204, 0));
        tf_emailM.setForeground(new java.awt.Color(0, 0, 0));
        tf_emailM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_senhaM.setBackground(new java.awt.Color(255, 204, 0));
        tf_senhaM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_senhaM.setForeground(new java.awt.Color(0, 0, 0));
        tf_senhaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senhaMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_cadMedicoLayout = new javax.swing.GroupLayout(jp_cadMedico);
        jp_cadMedico.setLayout(jp_cadMedicoLayout);
        jp_cadMedicoLayout.setHorizontalGroup(
            jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cadMedicoLayout.createSequentialGroup()
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_cadMedicoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_cadMedicoLayout.createSequentialGroup()
                                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_areaAtuanteM)
                                    .addComponent(jl_crmM)
                                    .addComponent(jl_emailM)
                                    .addComponent(jl_senhaM))
                                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_cadMedicoLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(tf_areaAtuanteM, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 5, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cadMedicoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_senhaM)
                                            .addComponent(tf_emailM, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jp_cadMedicoLayout.createSequentialGroup()
                                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_usuarioM)
                                    .addComponent(jl_nomeM))
                                .addGap(70, 70, 70)
                                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_nomeM, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_usuarioM, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cadMedicoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tf_crmM, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_cadMedicoLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jb_cadastrarM, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(168, 168, 168))
        );
        jp_cadMedicoLayout.setVerticalGroup(
            jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadMedicoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nomeM)
                    .addComponent(tf_nomeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_usuarioM)
                    .addComponent(tf_usuarioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_areaAtuanteM)
                    .addComponent(tf_areaAtuanteM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_crmM)
                    .addComponent(tf_crmM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_emailM)
                    .addComponent(tf_emailM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jp_cadMedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_senhaM)
                    .addComponent(tf_senhaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_cadastrarM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jtp_cadUsuarios.addTab("Médico", jp_cadMedico);

        jp_cadEnfermeira.setBackground(new java.awt.Color(10, 162, 255));
        jp_cadEnfermeira.setForeground(new java.awt.Color(255, 255, 255));

        jl_nomeE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_nomeE.setForeground(new java.awt.Color(255, 255, 255));
        jl_nomeE.setText("Nome:");

        jl_corenE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_corenE.setForeground(new java.awt.Color(255, 255, 255));
        jl_corenE.setText("COREN:");

        jl_usuarioE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_usuarioE.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuarioE.setText("Usuário:");

        jl_senhaE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_senhaE.setForeground(new java.awt.Color(255, 255, 255));
        jl_senhaE.setText("Senha:");

        jl_telefoneE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_telefoneE.setForeground(new java.awt.Color(255, 255, 255));
        jl_telefoneE.setText("Telefone:");

        jb_cadastrarE.setBackground(new java.awt.Color(255, 204, 0));
        jb_cadastrarE.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_cadastrarE.setForeground(new java.awt.Color(255, 255, 255));
        jb_cadastrarE.setText("Cadastrar");
        jb_cadastrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cadastrarEActionPerformed(evt);
            }
        });

        tf_nomeE.setBackground(new java.awt.Color(255, 204, 0));
        tf_nomeE.setForeground(new java.awt.Color(0, 0, 0));
        tf_nomeE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_nomeE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nomeEActionPerformed(evt);
            }
        });

        tf_usuarioE.setBackground(new java.awt.Color(255, 204, 0));
        tf_usuarioE.setForeground(new java.awt.Color(0, 0, 0));
        tf_usuarioE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tf_telefoneE.setBackground(new java.awt.Color(255, 204, 0));
        tf_telefoneE.setForeground(new java.awt.Color(0, 0, 0));
        tf_telefoneE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_telefoneE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telefoneEActionPerformed(evt);
            }
        });

        tf_corenE.setBackground(new java.awt.Color(255, 204, 0));
        tf_corenE.setForeground(new java.awt.Color(0, 0, 0));
        tf_corenE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        pf_senhaE.setBackground(new java.awt.Color(255, 204, 0));
        pf_senhaE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pf_senhaE.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jp_cadEnfermeiraLayout = new javax.swing.GroupLayout(jp_cadEnfermeira);
        jp_cadEnfermeira.setLayout(jp_cadEnfermeiraLayout);
        jp_cadEnfermeiraLayout.setHorizontalGroup(
            jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadEnfermeiraLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_nomeE)
                    .addComponent(jl_usuarioE)
                    .addComponent(jl_corenE)
                    .addComponent(jl_telefoneE)
                    .addComponent(jl_senhaE))
                .addGap(31, 31, 31)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_telefoneE, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(tf_usuarioE, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(tf_nomeE, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(tf_corenE, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(pf_senhaE))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cadEnfermeiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_cadastrarE, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(349, 349, 349))
        );
        jp_cadEnfermeiraLayout.setVerticalGroup(
            jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadEnfermeiraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nomeE)
                    .addComponent(tf_nomeE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_usuarioE)
                    .addComponent(tf_usuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_corenE)
                    .addComponent(tf_corenE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefoneE)
                    .addComponent(tf_telefoneE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jp_cadEnfermeiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_senhaE)
                    .addComponent(pf_senhaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jb_cadastrarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jtp_cadUsuarios.addTab("Enfermeira", jp_cadEnfermeira);

        javax.swing.GroupLayout jp_cadastrarLayout = new javax.swing.GroupLayout(jp_cadastrar);
        jp_cadastrar.setLayout(jp_cadastrarLayout);
        jp_cadastrarLayout.setHorizontalGroup(
            jp_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadastrarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtp_cadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1144, Short.MAX_VALUE))
        );
        jp_cadastrarLayout.setVerticalGroup(
            jp_cadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cadastrarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jtp_cadUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jtp_opcInicio.addTab("Cadastrar", jp_cadastrar);

        jp_entrarBackground.setBackground(new java.awt.Color(64, 89, 201));
        jp_entrarBackground.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(23, 142, 206)));

        jtp_entrarP.setBackground(new java.awt.Color(141, 194, 226));
        jtp_entrarP.setForeground(new java.awt.Color(255, 255, 255));
        jtp_entrarP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jp_entrar.setBackground(new java.awt.Color(10, 162, 255));
        jp_entrar.setForeground(new java.awt.Color(255, 255, 255));

        jl_email_tel_Entrar_P.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_email_tel_Entrar_P.setForeground(new java.awt.Color(255, 255, 255));
        jl_email_tel_Entrar_P.setText("E-mail:");

        jl_senha_Entrar_P.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jl_senha_Entrar_P.setForeground(new java.awt.Color(255, 255, 255));
        jl_senha_Entrar_P.setText("Senha:");

        jb_entrarP.setBackground(new java.awt.Color(255, 204, 0));
        jb_entrarP.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jb_entrarP.setForeground(new java.awt.Color(255, 255, 255));
        jb_entrarP.setText("Entrar");
        jb_entrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarPActionPerformed(evt);
            }
        });

        tf_email_Entrar_P.setBackground(new java.awt.Color(255, 204, 0));
        tf_email_Entrar_P.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_email_Entrar_P.setForeground(new java.awt.Color(0, 0, 0));

        tf_senha_Entrar_P.setBackground(new java.awt.Color(255, 204, 0));
        tf_senha_Entrar_P.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_senha_Entrar_P.setForeground(new java.awt.Color(0, 0, 0));
        tf_senha_Entrar_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_senha_Entrar_PActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_entrarLayout = new javax.swing.GroupLayout(jp_entrar);
        jp_entrar.setLayout(jp_entrarLayout);
        jp_entrarLayout.setHorizontalGroup(
            jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_entrarLayout.createSequentialGroup()
                .addGroup(jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_entrarLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(jb_entrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_entrarLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_email_tel_Entrar_P)
                            .addComponent(jl_senha_Entrar_P))
                        .addGap(91, 91, 91)
                        .addGroup(jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_email_Entrar_P, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(tf_senha_Entrar_P))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        jp_entrarLayout.setVerticalGroup(
            jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_entrarLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_email_tel_Entrar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_email_Entrar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jp_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_senha_Entrar_P, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_senha_Entrar_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jb_entrarP)
                .addGap(32, 32, 32))
        );

        jtp_entrarP.addTab("Paciente", jp_entrar);

        javax.swing.GroupLayout jp_entrarBackgroundLayout = new javax.swing.GroupLayout(jp_entrarBackground);
        jp_entrarBackground.setLayout(jp_entrarBackgroundLayout);
        jp_entrarBackgroundLayout.setHorizontalGroup(
            jp_entrarBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_entrarBackgroundLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jtp_entrarP)
                .addGap(37, 37, 37))
        );
        jp_entrarBackgroundLayout.setVerticalGroup(
            jp_entrarBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_entrarBackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtp_entrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jtp_opcInicio.addTab("Entrar", jp_entrarBackground);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jtp_opcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jtp_opcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_cpfPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfPActionPerformed

    }//GEN-LAST:event_tf_cpfPActionPerformed

    private void tf_idadePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idadePActionPerformed

    }//GEN-LAST:event_tf_idadePActionPerformed

    private void tf_nomePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomePActionPerformed

    }//GEN-LAST:event_tf_nomePActionPerformed

    private void tf_telefonePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefonePActionPerformed

    }//GEN-LAST:event_tf_telefonePActionPerformed

    private void jb_cadastrarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cadastrarPMouseClicked

        String pn = this.tf_nomeP.getText();
        String pe = this.tf_emailP.getText();
        int pi = Integer.parseInt(this.tf_idadeP.getText());
        int pt =  Integer.parseInt(this.tf_telefoneP.getText());
        String pen = this.tf_enderecoP.getText();
        String ps =  this.tf_senhaP.getText();
        String pcpf = this.tf_cpfP.getText();

        JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");

        Pessoa p = new Pessoa(){};
        Paciente pa = new Paciente();

        p.setNome(pn);
        p.setEmail(pe);
        p.setIdade(pi);
        pa.setTelefone(pt);
        p.setEndereco(pen);
        p.setSenha(ps);
        p.setCPF(pcpf);

        pessoas.add(p);
        pessoas.add(pa);

        System.out.println("[" + "Paciente" + "]" + "\nNome: " + p.getNome() + "\nEmail: " +  p.getEmail() + "\nSenha: " + p.getSenha() + "\nTelefone: " + pa.getTelefone()
            + "\nIdade: " + p.getIdade() + "\nEndereço: " + p.getEndereco()  + "\nCPF: " + p.getCPF());

    }//GEN-LAST:event_jb_cadastrarPMouseClicked

    private void jb_cadastrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarPActionPerformed

        
        
        
        String pn = this.tf_nomeP.getText();
        String pe = this.tf_emailP.getText();
        int pi = Integer.parseInt(this.tf_idadeP.getText());
        int pt =  Integer.parseInt(this.tf_telefoneP.getText());
        String pen = this.tf_enderecoP.getText();
        String ps =  this.tf_senhaP.getText();
        String pcpf = this.tf_cpfP.getText();

        JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");

        Pessoa p = new Pessoa(){};
        Paciente pa = new Paciente();

        p.setNome(pn);
        p.setEmail(pe);
        p.setIdade(pi);
        pa.setTelefone(pt);
        p.setEndereco(pen);
        p.setSenha(ps);
        p.setCPF(pcpf);

        pessoas.add(p);
        pessoas.add(pa);

        

        System.out.println("[" + "Paciente" + "]" + "\nNome: " + p.getNome() + "\nEmail: " +  p.getEmail() + "\nSenha: " + p.getSenha() + "\nTelefone: " + pa.getTelefone()
            + "\nIdade: " + p.getIdade() + "\nEndereço: " + p.getEndereco()  + "\nCPF: " + p.getCPF());

    }//GEN-LAST:event_jb_cadastrarPActionPerformed

    private void jb_cadastrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarMActionPerformed

        String mn = this.tf_nomeM.getText();
        String me = this.tf_emailM.getText();
        String aa = this.tf_areaAtuanteM.getText();
        int crm = Integer.parseInt(this.tf_crmM.getText());
        String ps =  this.tf_senhaM.getText();

        JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");

        Pessoa m = new Pessoa(){};
        Medico mm = new Medico();

        m.setNome(mn);
        m.setEmail(me);
        mm.setareaAtuante(aa);
        mm.setcrm(crm);
        m.setSenha(ps);

        pessoas.add(m);
        medicos.add(mm);

        System.out.println("[" + "Médico" + "]" + "\nNome: " + m.getNome() + "\nEmail: " +  m.getEmail() + "\nSenha: " + m.getSenha() + "\nÁrea Atuante: " + mm.getareaAtuante()
            + "\nCRM: " + mm.getcrm());
    }//GEN-LAST:event_jb_cadastrarMActionPerformed

    private void jb_cadastrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cadastrarEActionPerformed

        String en = this.tf_nomeE.getText();
        int et = Integer.parseInt(this.tf_telefoneE.getText());
        String eu = this.tf_usuarioE.getText();
        int coren = Integer.parseInt(this.tf_corenE.getText());
        String es =  this.pf_senhaE.getText();

        JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");

        Pessoa e = new Pessoa(){};
        Enfermeira ee = new Enfermeira();

        e.setNome(en);
        ee.setTelefone(et);
        e.setUsuario(eu);
        ee.setCoren(coren);
        e.setSenha(es);

        pessoas.add(e);
        pessoas.add(ee);

        System.out.println("[" + "Enfermeira" + "]" + "\nNome: " + e.getNome() + "\nEmail: " +  ee.getTelefone()+ "\nSenha: " + e.getSenha() +
            "\nCOREN: " + ee.getCoren());
    }//GEN-LAST:event_jb_cadastrarEActionPerformed

    private void tf_nomeEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nomeEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nomeEActionPerformed

    private void tf_telefoneEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telefoneEActionPerformed

    }//GEN-LAST:event_tf_telefoneEActionPerformed

    private void jb_entrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarPActionPerformed

        String entrarEmail = this.tf_email_Entrar_P.getText();
        String entrarSenha = this.tf_senha_Entrar_P.getText();
   
        if(entrarEmail.equalsIgnoreCase("jp@gmail.com") && entrarSenha.equalsIgnoreCase("senha123")){
        
        JOptionPane.showMessageDialog(null, "Registro encontrado!!!");
        DadosUsuario model = new DadosUsuario();
            model.setIdade(tf_idadeP.getText());
            JanelaCarteira verc = new JanelaCarteira();
            verc.exportarIdade(model); //Passando como parâmetro o objeto criado da classe que terá os métodos Gets e Sets na Classe JanelaCarteira
            verc.setVisible(true); 
            dispose();
        }
        
        else{
        
            JOptionPane.showMessageDialog(null, "Registro não encontrado!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
             
        }

        for(int i=0; i<pessoas.size(); i++){
        
        Pessoa pac = pessoas.get(i);

         if(entrarEmail.equalsIgnoreCase(pac.getEmail()) && entrarSenha.equalsIgnoreCase(pac.getSenha())){
        
         JOptionPane.showMessageDialog(null, "Registro encontrado!!!");
         

         DadosUsuario model = new DadosUsuario();
            model.setIdade(tf_idadeP.getText());
            JanelaCarteira verc = new JanelaCarteira();
            verc.exportarIdade(model); //Passando como parâmetro o objeto criado da classe que terá os métodos Gets e Sets na Classe JanelaCarteira
            verc.setVisible(true); 
            dispose();
         break;
        }
        
        
        
        else{
             JOptionPane.showMessageDialog(null, "Registro não encontrado!!!", "ERROR", JOptionPane.ERROR_MESSAGE);
             break;
         }
        
        }        

        
        
           
             
    }//GEN-LAST:event_jb_entrarPActionPerformed

    private void tf_senhaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senhaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senhaPActionPerformed

    private void tf_senhaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senhaMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senhaMActionPerformed

    private void tf_senha_Entrar_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_senha_Entrar_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_senha_Entrar_PActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SistemaHome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_cadastrarE;
    private javax.swing.JButton jb_cadastrarM;
    private javax.swing.JButton jb_cadastrarP;
    private javax.swing.JButton jb_entrarP;
    private javax.swing.JLabel jl_areaAtuanteM;
    private javax.swing.JLabel jl_corenE;
    private javax.swing.JLabel jl_cpfP;
    private javax.swing.JLabel jl_crmM;
    private javax.swing.JLabel jl_emailM;
    private javax.swing.JLabel jl_emailP;
    private javax.swing.JLabel jl_email_tel_Entrar_P;
    private javax.swing.JLabel jl_enderecoP;
    private javax.swing.JLabel jl_idadeP;
    private javax.swing.JLabel jl_logotipo;
    private javax.swing.JLabel jl_nomeE;
    private javax.swing.JLabel jl_nomeM;
    private javax.swing.JLabel jl_nomeP;
    private javax.swing.JLabel jl_nomehospital;
    private javax.swing.JLabel jl_senhaE;
    private javax.swing.JLabel jl_senhaM;
    private javax.swing.JLabel jl_senhaP;
    private javax.swing.JLabel jl_senha_Entrar_P;
    private javax.swing.JLabel jl_telefoneE;
    private javax.swing.JLabel jl_telefoneP;
    private javax.swing.JLabel jl_usuarioE;
    private javax.swing.JLabel jl_usuarioM;
    private javax.swing.JPanel jp_cadEnfermeira;
    private javax.swing.JPanel jp_cadMedico;
    private javax.swing.JPanel jp_cadPaciente;
    private javax.swing.JPanel jp_cadastrar;
    private javax.swing.JPanel jp_entrar;
    private javax.swing.JPanel jp_entrarBackground;
    private javax.swing.JPanel jp_inicio;
    private javax.swing.JTabbedPane jtp_cadUsuarios;
    private javax.swing.JTabbedPane jtp_entrarP;
    private javax.swing.JTabbedPane jtp_opcInicio;
    private javax.swing.JPasswordField pf_senhaE;
    private javax.swing.JFormattedTextField tf_areaAtuanteM;
    private javax.swing.JFormattedTextField tf_corenE;
    private javax.swing.JFormattedTextField tf_cpfP;
    private javax.swing.JFormattedTextField tf_crmM;
    private javax.swing.JFormattedTextField tf_emailM;
    private javax.swing.JFormattedTextField tf_emailP;
    private javax.swing.JTextField tf_email_Entrar_P;
    private javax.swing.JFormattedTextField tf_enderecoP;
    private javax.swing.JFormattedTextField tf_idadeP;
    private javax.swing.JFormattedTextField tf_nomeE;
    private javax.swing.JFormattedTextField tf_nomeM;
    private javax.swing.JFormattedTextField tf_nomeP;
    private javax.swing.JPasswordField tf_senhaM;
    private javax.swing.JPasswordField tf_senhaP;
    private javax.swing.JPasswordField tf_senha_Entrar_P;
    private javax.swing.JFormattedTextField tf_telefoneE;
    private javax.swing.JFormattedTextField tf_telefoneP;
    private javax.swing.JFormattedTextField tf_usuarioE;
    private javax.swing.JFormattedTextField tf_usuarioM;
    // End of variables declaration//GEN-END:variables
}
